# Generated by Django 4.2 on 2025-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.CharField(max_length=30)),
                ('movie_genre', models.CharField(choices=[('CF', 'Ciencia Ficción'), ('C', 'Comedia'), ('F', 'Fantasia'), ('D', 'Drama'), ('T', 'Terror'), ('A', 'Acción')], max_length=10)),
                ('name_director', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
